[global]
   workgroup = WORKGROUP
   security = user
   map to guest = never
   interfaces = lo tailscale0
   bind interfaces only = yes
   netbios name = debian-nas

[data]
   path = /mnt/data
   browsable = yes
   read only = no
   valid users = nas
   force user = nas
   force group = nas_share
   create mask = 0660
   directory mask = 0770
