metadata_dir = "/var/lib/garage/meta"
data_dir     = "/var/lib/garage/data"

db_engine          = "sqlite"
replication_factor = 1
consistency_mode   = "consistent"

# Generate with: openssl rand -hex 32
#rpc_secret      = "REPLACE_WITH_64_CHAR_HEX_STRING"
rpc_secret      = "8cb16e67dfeb22efa559bde0c0cd027bfb5cc2decc100ce6fab0582749a5a630"
rpc_bind_addr   = "127.0.0.1:3901"
rpc_public_addr = "127.0.0.1:3901"

[s3_api]
s3_region    = "garage"
api_bind_addr = "0.0.0.0:3900"

[admin]
api_bind_addr = "0.0.0.0:3903"